---
## Example for re-deploying existing instance: ansible-playbook deploy.yml --limit="prado.ceph.com" -e api_user=admin -e api_key=XXXXX

- hosts: all
  user: admin
  roles:
    - common
  vars:
     app_name: "prado"
     branch: "master"
     ansible_ssh_port: 2222
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
